;; -*- mode: org -*-
#+TITLE: Stumpwm configuration
#+AUTHOR: Cloud Strife (Spektrum_light, gear-piped, purity-interface, topological android GAR-XB/G-3778 id: MGlIGTfxzZ formula-spectre)
#+PROPERTY: header-args :tangle "~/.config/stumpwm/config" :mkdirp t :shebang ";; -*- mode: lisp -*- \n"
#+auto_tangle: t
*  this is my stumpwm configuration. batteries included, but not charged. please escuse my wonkiness on common lisp.  feel free to take this as inspiration and/or contribute!

  this is my stumpwm configuration. batteries included, but not charged. please escuse my wonkiness on common lisp.  feel free to take this as inspiration and/or contribute!
** load quicklisp
#+BEGIN_SRC lisp
#-quicklisp
(let ((quicklisp-init (merge-pathnames ".local/share/quicklisp/setup.lisp"
                                       (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
#+END_SRC

** load slynk/swank
#+BEGIN_SRC lisp
(ql:quickload '(:slynk
                :alexandria
                ))

(let ((server-running nil))
  (defcommand slynk () ()
    "Toggle the swank server on/off"
    (if server-running
        (progn
          (slynk:stop-server 4005)
          (echo-string
           (current-screen)
           "Stopping swank.")
          (setf server-running nil))
        (progn
          (slynk:create-server :port 4005
                               :dont-close t)
          (echo-string
           (current-screen)
           "Starting swank. M-x sly-connect RET RET, then (in-package stumpwm).")
          (setf server-running t)))))
#+END_SRC

** define some colors.
#+BEGIN_SRC lisp
(defvar *background* "#000000")
(set-module-dir "/usr/share/common-lisp/source/stumpwm-contrib/")
(defvar *foreground* "#FFFFFF")
#+END_SRC
** macros!
*** define a macro to make mapping to various maps (heh) easier
#+BEGIN_SRC lisp
(defmacro mmap (map key command)
  "a macro to make binding easier"
  `(define-key ,map (kbd ,key) ,command))
#+END_SRC
*** define a macro to shorten the alexandria curry functionall
#+BEGIN_SRC lisp
(defmacro curry (map)
  `(alexandria:curry #'define-key ,map))
#+END_SRC
** load some modules
#+BEGIN_SRC lisp
(load-module "pass")
#+END_SRC
** keybindings
***  make focus follow mouse
#+BEGIN_SRC lisp
(setf *mouse-focus-policy* :sloppy)
#+END_SRC

#+begin_src lisp
(defvar *emacs-application-keymap*
  (let ((m (make-sparse-keymap)))
    (dolist
        (emacs-map `(
                     (,(kbd "m") "emacs-magit")
                     (,(kbd "c") "emacs-calendar")
                     (,(kbd "C-s") "emacs-auto-slynk")))
      (apply (curry m) emacs-map))))

#+end_src
*** define a custom keymap for my most used applications
#+begin_src  lisp
(defvar *my-application-keymap*
  (let ((m (make-sparse-keymap)))
    (mmap m "b" "exec ~/.local/bin/bw/brave")
    (mmap m "M-d" "exec ~/.local/bin/bw/deltachat")
    (mmap m "d" "exec ~/.local/bin/bw/abaddon")
    (mmap m "D" "exec ~/.local/bin/bw/discord")
    (mmap m "f" "exec firefox")
    (mmap m "M-l" "exec ~/.local/bin/bw/lycheeslicer")
    (mmap m "s" "exec flatpak run com.valvesoftware.Steam ")
    (mmap m "S" "exec ~/.local/bin/bw/steam")
    (mmap m "t" "exec emacsclient -e '(telega t)'")
    (mmap m "T" "exec emacsclient -e '(telega-kill t)'")
    (mmap m "w" "exec ~/.local/bin/bw/whatsdesk")
    (mmap m "l" "exec ~/.local/bin/bw/librewolf")
    (mmap m "o" "exec ~/.local/bin/bw/obsidian")
    m))
#+END_SRC
#+BEGIN_SRC lisp
(set-prefix-key (kbd "s-x"))
#+END_SRC
*** activate which key mode, which could be helpful.
#+BEGIN_SRC lisp
(unless (which-key-mode)
  (which-key-mode))
#+END_SRC
*** undefine default bindings
#+begin_src  lisp
(undefine-key *root-map* (kbd "o"))
(dolist
    (default-bindings `(
                        (,(kbd "M-n")) (,(kbd "M-p")) (,(kbd "x"))
                        (,(kbd "a"))   (,(kbd "C-a")) (,(kbd ">"))
                        (,(kbd "s"))   (,(kbd "S"))  (,(kbd "o"))
                        (,(kbd "TAB")) (,(kbd "\"")) (,(kbd "!"))
                        ))
  (apply (alexandria:curry #'undefine-key *root-map*) default-bindings))
#+END_SRC
#+end_src
*** *root-map* keybindings, aka prefixed ones (see prefix-key)
#+BEGIN_SRC lisp
(dolist
    (root-map `(
                (,(kbd "x")       ,*my-application-keymap*)
                (,(kbd "s-x")     "pull-hidden-next")
                (,(kbd "1")       "only")
                (,(kbd "2")       "vsplit")
                (,(kbd "3")       "hsplit")
                (,(kbd "0")       "remove-split")
                (,(kbd "s-b")     "windowlist")
                (,(kbd "s")       "slynk")
                (,(kbd "d")       "time")
                (,(kbd "e")       "exec emacsclient -c")
                (,(kbd "E")       "emacs")
                (,(kbd "C-e")     ,*emacs-application-keymap*)
                (,(kbd "X")       "exec killall xmobar tiramisu && xmobar")
                (,(kbd "s-h")     "move-window left")
                (,(kbd "s-j")     "move-window down")
                (,(kbd "s-k")     "move-window up")
                (,(kbd "s-l")     "move-window right")
                ))
  (apply (curry *root-map*) root-map))
#+END_SRC
*** *top-level* keybindings, aka with no prefix
#+BEGIN_SRC lisp
  (dolist
      (top-bindings `(
  ;                    (,(kbd "s-RET")     "exec emacsclient -ce '(+vterm/here \"~/\")'")
                      (,(kbd "s-RET")     "exec termonad")
                      (,(kbd "s-h")       "move-focus left")
                      (,(kbd "s-j")       "move-focus down")
                      (,(kbd "s-k")       "move-focus up")
                      (,(kbd "s-l")       "move-focus right")
                      (,(kbd "s-p")       "exec")
                      (,(kbd "s-r")       "loadrc")
                      (,(kbd "s-:")       "eval")
                      (,(kbd "s-u")       "pass:pass-copy")))
      (apply (curry *top-map*) top-bindings))
#+END_SRC
** initalization
things that have to be ran on startup.
the dbus thing is a crutch.

#+BEGIN_SRC lisp
(when *initializing*
  (run-shell-command "xmobar")
  (run-shell-command "sh ~/.fehbg"))
#+END_SRC
