#!/bin/sh
greenclip print | sed '/^$/d' | dmenu -i -l 10 -p clipboard | xargs -r -d'\n' -I '{}' greenclip print '{}'
#rofi -location 2 -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
